name: Flutter Web Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'  # Specify Flutter version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Build Flutter web
      - name: Build Flutter Web
        run: flutter build web --release

      # Step 5: Fix asset directory content
      - name: Fix asset directory contents
        run: |
          mv build/web/assets/assets/* build/web/assets
          rmdir build/web/assets/assets

      # Step 6: Modify base href in index.html
      - name: Modify base href
        run: sed -i 's|<base href="/">|<base href="/portfolio/">|' build/web/index.html

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Use your PAT here
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
